### ISSUE TITLE
Accuracy regressions compared to upstream

### ISSUE THREAD

**Issue by simias** [libretro/beetle-psx-libretro#308]
Somebody ran the accuracy tests on both mednafen and beetle and it seems to uncover many inaccuracies:

Mednafen tests: https://imgur.com/a/lWct8
Beetle tests: https://imgur.com/a/xsZYI

This is especially surprising for the CPU and GTE tests since as far as I know there aren't any significant modifications in beetle (having issues with the GPU is less surprising given the amount of hacking for hardware rendering/increased IR).

**Comment by MarcoEstevez** [comment]
Don't know if that is related, but when I did test Asuncia: Matsue no Jubaku (english patched), on retroach, did not go Ingame, I thought was related with patch itself, but I tested on mednafen with no issues.

I got same problem behabiour HW and non HW cores.

**Comment by OptimalJew** [comment]
Finished off the albums with the rest of the tests. Spoilers: Everything looks fine on the GPU front. I'll create a new album for Beetle and do it all over again once you guys are done doing what you're doing.

**Comment by simias** [comment]
@twinaphex  managed to fix the GTE regressions and I updated the CPU code to match upstream, it seems to pass the tests now.

**Comment by simias** [comment]
@OptimalJew feel free to update to the latest version, it should fix the GTE and CPX tests (at least it does on my side).

**Comment by OptimalJew** [comment]
@simias CPX is good to go, and GTE is greatly improved, but I'm still getting some failures.
![beetle cpx](https://user-images.githubusercontent.com/31424143/36521031-8d6935de-1762-11e8-80e8-cdec81bc6c4e.png)
![beetle gte opcode](https://user-images.githubusercontent.com/31424143/36521041-9b382346-1762-11e8-89d8-58871e54d32a.png)

**Comment by simias** [comment]
Uh, odd, I thought they all passed on my end. You're sure you've disabled all enhancements/hacks? (PGXP, overclocking etc...)

I'll double check.

**Comment by OptimalJew** [comment]
All tests were conducted on a separate, fresh instance of Retroarch. Settings were untouched, this is what was used: [retroarch-core-options.txt](https://github.com/libretro/beetle-psx-libretro/files/1748144/retroarch-core-options.txt)

**Comment by twinaphex** [comment]
@simias I think when you rebackported some of my speedhacks for GTE, you reintroduced the errors with RTPS/RTPT.

**Comment by simias** [comment]
Seems like it. I might have gotten mixed up between the hw and non-hw core (i.e. modifying one and testing the other).

**Comment by simias** [comment]
Fun fact: running the GTE test through the GL renderer segfaults.

**Comment by simias** [comment]
Okay, this time we should be good, at least GTE-wise (I couldn't be bothered for the MVMVA test to finish):

![psxtest_gte-180224-001738](https://user-images.githubusercontent.com/7925386/36621404-2f3b48de-18f8-11e8-98b2-7553cc69a4e7.png)

**Comment by OptimalJew** [comment]
@simias Finished the entire test suite on 7a7ae88 https://imgur.com/a/f0FTS

You did it, beetle now passes every test that mednafen does.

**Comment by simias** [comment]
Great, thank you for double checking!
