### ISSUE TITLE
[OpenGL] Castlevania Chronicles - Character Sprite Line & Broken Backgrounds

### ISSUE THREAD

**Issue by Papermanzero** [libretro/beetle-psx-libretro#351]
Settings

Renderer: Hardware (OpenGL)
Software Framebuffer: Off
Adaptive Smoothing: Off
Internal GPU Resolution: 4x
Texture filtering: bilinear
Internal Color depth: 32bpp
Wireframe Mode: Off
Display Full VRAM: Off
PGXP operation mode: Memory only
PGXP vertex cache: On
PGXP perspective correct texturing: On
Widescreen mode hack: Off
Frame duping: Off
CPU Frequency Scaling: 100%
GTE Overclock: Off
GPU rasterizer overclock: 1x
Skip Bios: Off
Dithering pattern: 1x
Display interal FPS: Off
Initial scanline: 0
Last scanline: 239
Initial scanline PAL: 0
Last scanline PAL: 287
Crop Overscan: On
Additional Cropping: Off
Offset Cropped Image: Off
DualShock Analog button toggle: Off
Port 1 Multitap: Off
Port 2 Multitap: Off
Gun Cursoer: Cross
Mouse Sensitivity: 100%
CD Access Method: sync
Memcard 0 method: libretro
Enable memory card 1: on
Shared memcards: off
Increase cd loading speed: 2x

GPU: Nvidia 760 GTX

Description: The main character in CC (PAL) has a verticle line in front of him which does not disappear. Moreover some backgrounds are broken (like water).

Screenshots:
![castlevania chronicles-180624-210501](https://user-images.githubusercontent.com/10263536/41823012-ecde3e14-77f8-11e8-8eab-f758ab972096.png)
![castlevania chronicles-180624-210705](https://user-images.githubusercontent.com/10263536/41823016-f5de9798-77f8-11e8-979f-5fbe73369b75.png)

**Comment by twinaphex** [comment]
Please turn off PGXP vertex caching. It does more harm than good in most games.

**Comment by Papermanzero** [comment]
Partially fixed with  a8aa726. The line in front of the character is still visible.
PGXP is disabled, vertex cache disabled, framebuffer enabled.

**Comment by Papermanzero** [comment]
Also this issue is still present with the latest commit.

**Comment by twinaphex** [comment]
Yeah, the issue is still there with the latest commit.

@iCatButler Probably a nice edge case issue as far as sprites are concerned.

**Comment by iCatButler** [comment]
@twinaphex this should have been fixed by the last couple of commits. Those lines don't appear with my local build, but do appear if I download the latest via Retroarch.

Looking at the nightly builds the latest for this core is timestamped 2018-07-02, so it could be that the changes haven't triggered a fresh build.

**Comment by Papermanzero** [comment]
I downloaded the latest build via Retroarch and can still see the issues.
Maybe it is a build issue

**Comment by Papermanzero** [comment]
Issue is fixed with  6094309
