### ISSUE TITLE
Constructor Flickering on Beetle PSX Cores

### ISSUE THREAD

**Issue by TradeDraft** [libretro/beetle-psx-libretro#707]
# First and foremost consider this:
- This is a DEVELOPER oriented channel dedicated to report bugs and suggest features about the libretro core, please do not ask for help. If you need help, go to https://forums.libretro.com/;
- The upstream bug tracker is a forum thread, located at https://forum.fobby.net/index.php?t=msg&th=1114;
    - Note: As of October 2018, Microsoft email providers (think email addresses ending with hotmail/live/outlook) are rejecting email from the forum. If you want to register an account in the upstream project's forum, consider using another mail provider.
- For game-related bugs:
    1) First, check if it's already reported on the upstream bug tracker;
    2) If it's not reported there, try to reproduce the bug with mednafen;
    3) If it's reproducible with mednafen, report it on the upstream bugtracker;
    4) If it's not reproducible with mednafen, ONLY THEN should you report it here.
    5) DO NOT report Beetle-specific bugs on the upstream tracker.

## Description

Flickers during Gameplay.

Video Showing It:

https://www.youtube.com/watch?v=qnDDLNf-mwc

and

https://www.youtube.com/watch?v=J2NKOj7s1Ls

### Expected behavior

To be no Flickers at all

### Actual behavior

Video Showing It:

https://www.youtube.com/watch?v=qnDDLNf-mwc

and

https://www.youtube.com/watch?v=J2NKOj7s1Ls

### Steps to reproduce the bug

Just Load into Game Normally

### Bisect results

[Try to bisect and tell us when this started happening]

### Version/Commit

Latest of Both Beetle PSX and Beetle PSX HW

### Core options

Default Options

### Environment information

- Frontend: Retroarch 1.9.0
- OS: Windows 10 Home
- Compiler: [In case you are running local builds]
- GPU: Intel i7-8700t 2.40ghz

**Comment by xzn** [comment]
I'm guessing the problem is that the hardware rendererr scanout framebuffer all at once instead of following the scanlines. So this is a vsync emulation bug. I'll try to resolve this in my branch.

**Comment by TradeDraft** [comment]
Here is a Update Video showing some Flickering is gone but Not All

https://www.youtube.com/watch?v=fQZkII_yEkA

**Comment by xzn** [comment]
Can you manually install core? [Give this a try.](https://github.com/xzn/beetle-psx-libretro/releases/download/wip/mednafen_psx_hw_libretro.zip) I may refactor and submit a PR if testing goes well.

The ground texture is still weird though. I'm not good at writing shaders so no quick fix from me for now :(

**Comment by TradeDraft** [comment]
Okay I did add that Core Manually and the Same Thing happens as Video Shows:

https://www.youtube.com/watch?v=Sc58H8Oc__0

Is there somewhere I can ask about Shaders for this?

**Comment by xzn** [comment]
As a serious suggestion just software mode for now.

After changing the setting, close and reopen the game and it should works.

OTOH where did you install the core? Did you overwrite the existing file (after backing it up)? It fixed the issue on my end so I don't know why it doesn't work you..

**Comment by TradeDraft** [comment]
I have tried the Sofware Mode and the Normal Beetle PSX Core and Same Thing happens with the Flickering. Even does it in the Menu Screen when you choose how you going to play and who is Playing.

I just overwrited it from the Zip FIle on 1 and Anoher thru the Updated in the Retroarch Program.

**Comment by xzn** [comment]
The official core has not been updated, updating through the in-game menu will not work.

The one I uploaded is a work in progress but the flickering should have been fixed.
Extract the file `mednafen_psx_hw_libretro.dll` to `C:\Users\[username]\AppData\Roaming\RetroArch\cores` to test it out.

Sorry about the confusion :o

**Comment by TradeDraft** [comment]
Yeah I used the Core File from the Zip File you linked above?

Put it in the RA 1.9.0 Core Folder but still getting the Ground Flickering

**Comment by xzn** [comment]
Interesting, do you have save state to the level you are playing? I'm not getting any more flickering on my end so I don't know what's going on..

:o

**Comment by TradeDraft** [comment]
I am on 1st Level.

Tried using a Saved Game and Now I get Flicking in the Menu on the Right. 

The Ground 1 has stoppee.

Would I need to change anything in the Options?

**Comment by xzn** [comment]
I suggest restoring the original official core. I can't really help you since I can't reproduce the problem on my end. Sorry..

**Comment by TradeDraft** [comment]
I had that Problem at home even. We have few different Computers and there could be Difference Performance between them.

Can be very Annoying.

So would then Updates of the Core in future be on the Buildbot?

**Comment by xzn** [comment]
[mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/5152451/mednafen_psx_hw_libretro.zip)

I've managed to get rid of the bad ground texture for Vulkan at 1x resolution scale. It now looks as good as software mode but without flickering.

![image](https://user-images.githubusercontent.com/1617680/91764402-9fbc2a80-ebad-11ea-9f85-af7fe5a448bf.png)

If you find installing a custom core troublesome I recommended the latest [Duckstation](https://github.com/stenzek/duckstation/releases) since it appears to not flicker at all.

P.S. for the update to be on build bot I have to submit a PR and for them to approve it. The code is a bit messy though and need refactoring so it will be a while.

Settings screen:
![image](https://user-images.githubusercontent.com/1617680/91764858-633cfe80-ebae-11ea-8aca-081e402f9bd8.png)

**Comment by TradeDraft** [comment]
Tried that and It worked Great.

I tried Duckstation but I want to use the PS1 Mouse with this game and Can't do that on the Core yet.

I been using PSX ReArmed at the Moment

**Comment by TradeDraft** [comment]
Just tried this Game again and the same Issue is back again

As in Game the Building Flashes in Game.

That is using Vulkan

Open GL has lot of Dots on the Screen

Seems to work fine with Software Video Render
